version: "3.3"
networks:
  net:
    external: true
services:
  notes-database: # Mongo database
    image: mongo-database
    container_name: mongo-database
    ports:
      - 27017:27017 
      - 28017:28017
    networks:
      - net
    environment:
      - CATALINA_OPTS=-Xmx206M -Xms128M -XX:MaxPermSize=50M
    deploy:
      resources:
        limits:
          memory: 256M
  auth-api: # Authentication API (Spring)
    image: auth-api
    container_name: auth-api
    ports:
      - 8083:8080
    networks:
      - net
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "VAULT_TOKEN=s8ynaMrJvQPVq2BEPRxgceHcG"
      - "DATASOURCE_URL=jdbc:mysql://mysql-database:3306/usersdb"
      - CATALINA_OPTS=-Xmx206M -Xms128M -XX:MaxPermSize=50M
    deploy:
      resources:
        limits:
          memory: 384M
  mysql-database:
    image: mysql-database
    container_name: mysql-database
    ports:
      - 3306:3306
    networks:
      - net
    environment:
      - CATALINA_OPTS=-Xmx206M -Xms128M -XX:MaxPermSize=50M
    deploy:
      resources:
        limits:
          memory: 256M
  email-api:
    image: email-api
    container_name: email-api
    ports:
      - 8084:8080
    networks:
      - net
    environment:
      - CATALINA_OPTS=-Xmx106M -Xms64M -XX:MaxPermSize=50M
    deploy:
      resources:
        limits:
          memory: 256M


