version: "3.3"
services:
  notes-database:
    image: mongo-database
    container_name: mongo-database
    ports:
      - 27017:27017 
      - 28017:28017
    environment:
      - MONGO_INITDB_DATABASE=notesdb 
      - CATALINA_OPTS=-Xmx206M -Xms128M -XX:MaxPermSize=50M
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 256M
    # All scripts in docker-entrypoint-initdb.d/ are automatically executed 
    # during container startup when the database folder is empty.
    volumes:
      - ./scripts/mongo-scripts:/docker-entrypoint-initdb.d/
      - mongo-database-data:/data/db
  auth-mock:
    build:
      context: ./json-server-mock
      dockerfile: Dockerfile
    command: node index.js
    environment:
      - PORT=8083
    ports:
      - 8083:8083
networks:
  default:
    external:
      name: net
volumes:
  mongo-database-data:
    external: false