version: "3.3"
services:
  notes-database: # Mongo database
    image: mongo-database
    container_name: mongo-database
    ports:
      - 27017:27017 
      - 28017:28017
    network_mode: host
    environment:
      - CATALINA_OPTS=-Xmx206M -Xms128M -XX:MaxPermSize=50M
    deploy:
      resources:
        limits:
          memory: 256M
  auth-api: # Authentication API (Spring)
    image: auth-api
    container_name: auth-api
    ports:
      - 8083:8083
    network_mode: host
    environment:
      - "DBSERVICEPORT=3306"
      - "DBSERVICENAME=127.0.0.1"
      - "PORT=8083"
      - "SPRING_PROFILES_ACTIVE=${PROFILE}"
      - "VAULT_TOKEN=s8ynaMrJvQPVq2BEPRxgceHcG"
      - CATALINA_OPTS=-Xmx206M -Xms128M -XX:MaxPermSize=50M
    deploy:
      resources:
        limits:
          memory: 384M
  mysql-database:
    image: mysql-database
    container_name: mysql-database
    ports:
      - 3306:3306
    network_mode: host
    environment:
      - CATALINA_OPTS=-Xmx206M -Xms128M -XX:MaxPermSize=50M
    deploy:
      resources:
        limits:
          memory: 256M
  email-api:
    image: email-api
    container_name: email-api
    ports:
      - 8084:8084
    network_mode: host
    environment:
      - CATALINA_OPTS=-Xmx106M -Xms64M -XX:MaxPermSize=50M
    deploy:
      resources:
        limits:
          memory: 256M