spring:
  application:
    name: notes-api
  data:
    web:
      pageable:
        max-page-size: 40
  jmx:
    enabled: false
  profiles:
    active: '@activatedProperties@'
  boot:
    admin:
      client:
        url: http://localhost:8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/ 
management:
  endpoints:
    web:
      exposure:
        include: '*'
    
urls:
  auth:
    check-token: ${AUTH_API_URL:http://notes-api_auth-mock_1:8083}/token/check
    create-token: ${AUTH_API_URL:http://notes-api_auth-mock_1:8083}/token
